=== SwissFederalArchives/cmi-viaduc-backend/Test/Manager/Asset.Tests/TestData/IiifSourceData/30653558/header/gebrauchskopie.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 U (http://www.xmlspy.com) by XMLSPY 2005 Professional Ed., Installed for 5 users (Schweiz Landesbibliothek) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:viaduc="http://bar.admin.ch/gebrauchskopie/v1" xmlns="http://bar.admin.ch/gebrauchskopie/v1"
  targetNamespace="http://bar.admin.ch/gebrauchskopie/v1" elementFormDefault="qualified" attributeFormDefault="unqualified" version="4.1">
  <xs:include schemaLocation="ablieferung.xsd"/>
  <xs:include schemaLocation="paket.xsd"/>
  <xs:include schemaLocation="provenienz.xsd"/>
  <xs:include schemaLocation="ordnungssystem.xsd"/>
  <xs:include schemaLocation="ordnungssystemposition.xsd"/>
  <xs:include schemaLocation="dossier.xsd"/>
  <xs:include schemaLocation="dokument.xsd"/>
  <xs:include schemaLocation="ordner.xsd"/>
  <xs:include schemaLocation="datei.xsd"/>
  <xs:include schemaLocation="archivischerVorgang.xsd"/>
  <xs:include schemaLocation="zusatzDaten.xsd"/>
  <xs:element name="paket" type="paket"/>
  <xs:complexType name="paket" abstract="true">
    <xs:sequence>
      <xs:element name="generierungsdatum" type="xs:dateTime"/>
      <xs:element minOccurs="0" name="bestellinformation" type="text4"/>
    </xs:sequence>
    <xs:attribute name="schemaVersion" type="schemaVersion" use="required"/>
  </xs:complexType>

  <xs:complexType name="paketDIP">
    <xs:complexContent>
      <xs:extension base="paket">
        <xs:sequence>
          <xs:element name="inhaltsverzeichnis" type="inhaltsverzeichnisDIP"/>
          <xs:element name="ablieferung" type="ablieferungDIP"/>
          <xs:element maxOccurs="unbounded" minOccurs="0" name="archivischerVorgang" type="archivischerVorgang"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="archivischerVorgang">
    <xs:sequence>
      <xs:element name="vorgangstyp" type="vorgangstyp"/>
      <xs:element name="beschreibung" type="beschreibung"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ablieferung" abstract="true">
    <xs:sequence>
      <xs:element name="ablieferungstyp" type="ablieferungstyp"/>
      <xs:element name="ablieferndeStelle" type="ablieferndeStelle"/>
      <xs:element name="entstehungszeitraum" type="historischerZeitraum" minOccurs="0">
        <xs:annotation>
          <xs:documentation xml:lang="de">Der Entstehungszeitraum der Ablieferung wird aus dem ältesten Entstehungsdatum und dem jüngsten Datum der Dokumente oder Dateien ermittelt, die der Ablieferung zugeordneten  sind. Der Zeitraum kann auch geschätzt sein.</xs:documentation>
          <xs:documentation xml:lang="en">The creation period of the submission is calculated from the earliest creation date and the most recent date of the documents or files allocated to the submission. The period may also be estimated.</xs:documentation>
          <xs:documentation xml:lang="fr">La période de création du versement est déterminée par la date de création la plus ancienne et par la date la plus récente des documents ou des fichiers , qui sont attribués au versement. La période peut aussi être estimée</xs:documentation>
          <xs:documentation xml:lang="it"/>
        </xs:annotation>
      </xs:element>
      <xs:element name="bemerkung" type="bemerkungAblieferung" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ablieferungDIP">
    <xs:complexContent>
      <xs:extension base="ablieferung">
        <xs:sequence>
          <xs:element name="ablieferungsnummer" type="ablieferungsnummer" minOccurs="0"/>
          <xs:element name="provenienz" type="provenienzDIP"/>
          <xs:element name="ordnungssystem" type="ordnungssystemDIP"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="provenienz" abstract="true">
    <xs:sequence>
      <xs:element name="aktenbildnerName" type="aktenbildnerName"/>
      <xs:element name="systemName" type="systemName" minOccurs="0"/>
      <xs:element name="systemBeschreibung" type="systemBeschreibung" minOccurs="0"/>
      <xs:element name="verwandteSysteme" type="verwandteSysteme" minOccurs="0"/>
      <xs:element name="archivierungsmodusLoeschvorschriften" type="archivierungsmodusLoeschvorschriften" minOccurs="0"/>
      <xs:element name="registratur" type="registratur" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="provenienzDIP">
    <xs:complexContent>
      <xs:extension base="provenienz"> </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="ordnungssystem" abstract="true">
    <xs:sequence>
      <xs:element name="name" type="nameOrdnungssystem"/>
      <xs:element name="generation" type="generation" minOccurs="0"/>
      <xs:element name="mitbenutzung" type="mitbenutzung" minOccurs="0"/>
      <xs:element name="bemerkung" type="bemerkungOrdnungssysstem" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ordnungssystemDIP">
    <xs:complexContent>
      <xs:extension base="ordnungssystem">
        <xs:sequence>
          <xs:element name="ordnungssystemposition" type="ordnungssystempositionDIP" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="ordnungssystemposition" abstract="true">
    <xs:sequence>
      <xs:element name="nummer" type="nummer" minOccurs="0"/>
      <xs:element name="titel" type="titelOrdnungssystemposition" minOccurs="0"/>
      <xs:element name="federfuehrendeOrganisationseinheit" type="federfuehrendeOrganisationseinheitOrdnungssystemposition" minOccurs="0"/>
      <xs:element name="klassifizierungskategorie" type="klassifizierungskategorieOrdnungssystemposition" minOccurs="0"/>
      <xs:element name="datenschutz" type="datenschutzOrdnungssystemposition" minOccurs="0"/>
      <xs:element name="oeffentlichkeitsstatus" type="oeffentlichkeitsstatusOrdnungssystemposition" minOccurs="0"/>
      <xs:element name="oeffentlichkeitsstatusBegruendung" type="oeffentlichkeitsstatusBegruendungOrdnungssystemposition" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ordnungssystempositionDIP">
    <xs:complexContent>
      <xs:extension base="ordnungssystemposition">
        <xs:sequence>
          <xs:element name="ordnungssystemposition" type="ordnungssystempositionDIP" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element name="dossier" type="dossierDIP" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="idOrdnungssystemposition" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="dossier" abstract="true">
    <xs:sequence>
      <xs:element name="aktenzeichen" type="aktenzeichen" minOccurs="0"/>
      <xs:element name="zusatzmerkmal" type="zusatzmerkmal" minOccurs="0"/>
      <xs:element name="titel" type="titelDossier"/>
      <xs:element name="inhalt" type="inhalt" minOccurs="0"/>
      <xs:element name="erscheinungsform" type="erscheinungsformDossier" minOccurs="0"/>
      <xs:element name="umfang" type="umfangDossier" minOccurs="0"/>
      <xs:element name="federfuehrendeOrganisationseinheit" type="federfuehrendeOrganisationseinheitDossier" minOccurs="0"/>
      <xs:element name="eroeffnungsdatum" type="historischerZeitpunkt" minOccurs="0">
        <xs:annotation>
          <xs:documentation xml:lang="de">Zeitpunkt, an dem das Dossier eröffnet worden ist.</xs:documentation>
          <xs:documentation xml:lang="en">Time point at which the dossier was opened.</xs:documentation>
          <xs:documentation xml:lang="fr">Moment où le dossier a été ouvert.</xs:documentation>
          <xs:documentation xml:lang="it"/>
        </xs:annotation>
      </xs:element>
      <xs:element name="abschlussdatum" type="historischerZeitpunkt" minOccurs="0">
        <xs:annotation>
          <xs:documentation xml:lang="de">Zeitpunkt, an dem das Dossier abgeschlossen worden ist.</xs:documentation>
          <xs:documentation xml:lang="en">Time point at which the dossier was opened.</xs:documentation>
          <xs:documentation xml:lang="fr">Moment où le dossier a été clos.</xs:documentation>
          <xs:documentation xml:lang="it"/>
        </xs:annotation>
      </xs:element>
      <xs:element name="entstehungszeitraum" type="historischerZeitraum">
        <xs:annotation>
          <xs:documentation xml:lang="de">Der Entstehungszeitraum des Dossiers wird aus dem ältesten Entstehungsdatum und dem jüngsten (Änderungs)datum aller dem Dossier zugeordneten Dokumente oder Dateien ermittelt. Der Zeitraum kann auch geschätzt sein.</xs:documentation>
          <xs:documentation xml:lang="en">The creation period of the dossier is calculated from the earliest creation date and the most recent (change) date of all the documents or files allocated to the dossier. The period may also be estimated.</xs:documentation>
          <xs:documentation xml:lang="fr">La période de création du dossier est déterminée par la date de création la plus ancienne et par la date (de modification) la plus récente de tous les documents ou fichiers attribués au dossier. La période peut aussi être estimée.</xs:documentation>
          <xs:documentation xml:lang="it"/>
        </xs:annotation>
      </xs:element>
      <xs:element name="entstehungszeitraumAnmerkung" type="entstehungszeitraumAnmerkung" minOccurs="0"/>
      <xs:element name="klassifizierungskategorie" type="klassifizierungskategorieDossier" minOccurs="0"/>
      <xs:element name="datenschutz" type="datenschutzDossier" minOccurs="0"/>
      <xs:element name="oeffentlichkeitsstatus" type="oeffentlichkeitsstatusDossier" minOccurs="0"/>
      <xs:element name="oeffentlichkeitsstatusBegruendung" type="oeffentlichkeitsstatusBegruendungDossier" minOccurs="0"/>
      <xs:element name="sonstigeBestimmungen" type="sonstigeBestimmungenDossier" minOccurs="0"/>
      <xs:element name="vorgang" type="vorgangAktivitaet" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation xml:lang="de">Vorgangsobjekte repräsentieren einzelne, abgrenzbare Geschäftsfälle. Der Vorgang wird durchgeführt über eine Folge von einzelnen Aktivitäten. Einer einzelnen Aktivität sind in der Regel ein federführender Akteur zugewiesen.</xs:documentation>
          <xs:documentation xml:lang="en">Process representing separately identifiable business cases . A process is performed through a sequence of individual operations. To each single activity is usually leading actorassigned.</xs:documentation>
          <xs:documentation xml:lang="fr">Les objets du processus représentent des cas particuliers délimitables</xs:documentation>
          <xs:documentation xml:lang="it"/>
        </xs:annotation>
      </xs:element>
      <xs:element name="bemerkung" type="bemerkungDossier" minOccurs="0"/>
      <xs:element name="zusatzDaten" type="zusatzDaten" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="id" type="idDossier" use="required"/>
  </xs:complexType>

  <xs:complexType name="dossierDIP" abstract="false">
    <xs:complexContent>
      <xs:extension base="dossier">
        <xs:sequence>
          <xs:element name="dossier" type="dossierDIP" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element name="dokument" type="dokumentDIP" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element name="dateiRef" type="dateiRef" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="vorgangAktivitaet" mixed="true">
    <xs:sequence minOccurs="0">
      <xs:element name="titel" type="titelVorgang"/>
      <xs:element name="arbeitsanweisung" type="arbeitsanweisungVorgang" minOccurs="0"/>
      <xs:element name="federfuehrung" type="federfuehrungVorgang" minOccurs="0"/>
      <xs:element name="verweis" type="verweisVorgang" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="bemerkung" type="bemerkungVorgang" minOccurs="0"/>
      <xs:element name="zusatzDaten" type="zusatzDaten" minOccurs="0"/>
      <xs:element name="aktivitaet" type="aktivitaet" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="order" type="orderVorgang" use="optional"/>
  </xs:complexType>

  <xs:complexType name="aktivitaet">
    <xs:sequence>
      <xs:sequence>
        <xs:element name="vorschreibung" type="vorschreibungAktivitaet"/>
        <xs:element name="anweisung" type="anweisungAktivitaet" minOccurs="0"/>
        <xs:element name="bearbeiter" type="bearbeiterAktivitaet" minOccurs="0"/>
        <xs:element name="abschlussdatum" type="abschlussdatumAktivitaet" minOccurs="0"/>
        <xs:element name="verweis" type="verweisAktivitaet" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="bemerkung" type="bemerkungAktivitaet" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="zusatzDaten" type="zusatzDaten" minOccurs="0"/>
      </xs:sequence>
    </xs:sequence>
    <xs:attribute name="order" type="orderAktivitaet" use="optional"/>
  </xs:complexType>

  <xs:simpleType name="dateiRef">
    <xs:restriction base="xs:IDREFS">
      <xs:length value="1"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="dokument" abstract="true">
    <xs:sequence>
      <xs:element name="titel" type="titelDokument"/>
      <xs:element name="erscheinungsform" type="erscheinungsformDokument"/>
      <xs:element name="registrierdatum" type="historischerZeitpunkt" minOccurs="0">
        <xs:annotation>
          <xs:documentation xml:lang="de">Zeitpunkt an welchem das Dokument im System einem Dossier zugeordnet worden ist.</xs:documentation>
          <xs:documentation xml:lang="en">Time point at which a document was added to the dossier.</xs:documentation>
          <xs:documentation xml:lang="fr">Moment où le document est attribué à un dossier dans le système.</xs:documentation>
          <xs:documentation xml:lang="it"/>
        </xs:annotation>
      </xs:element>
      <xs:element name="entstehungszeitraum" type="historischerZeitraum" minOccurs="0">
        <xs:annotation>
          <xs:documentation xml:lang="de">Zeitliche Angabe über die Entstehung des Dokuments. Als Entstehung des Dokuments kann das Datum seiner Erstellung angegeben werden, oder den Zeitraum, in dem das Dokument entstanden ist (aus dem ältesten Entstehungsdatum und dem jüngsten Datum des Dokuments ermittelt). Der Zeitraum kann auch geschätzt sein.</xs:documentation>
          <xs:documentation xml:lang="en">Period of the origin of the document. As creation time of the document the date of its creation can be specified, or the period in which the document was created (determined from the oldest creation date and the most recent date of the document) . The period can also be estimated.</xs:documentation>
          <xs:documentation xml:lang="fr">Indications temporelles sur la création du document. Comme création du document peut être indiquée la date de son élaboration ou la période durant laquelle le document a été créé (déterminée par la date de création la plus ancienne et par la date du document le plus récent). La période peut aussi être estimée.</xs:documentation>
          <xs:documentation xml:lang="it"/>
        </xs:annotation>
      </xs:element>
      <xs:element name="klassifizierungskategorie" type="klassifizierungskategorieDokument" minOccurs="0"/>
      <xs:element name="datenschutz" type="datenschutzDokument" minOccurs="0"/>
      <xs:element name="oeffentlichkeitsstatus" type="oeffentlichkeitsstatusDokument" minOccurs="0"/>
      <xs:element name="oeffentlichkeitsstatusBegruendung" type="oeffentlichkeitsstatusBegruendungDokument" minOccurs="0"/>
      <xs:element name="sonstigeBestimmungen" type="sonstigeBestimmungenDokument" minOccurs="0"/>
      <xs:element name="bemerkung" type="bemerkungDokument" minOccurs="0"/>
      <xs:element name="zusatzDaten" type="zusatzDaten" minOccurs="0"/>
      <xs:element name="dateiRef" type="dateiRef" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="id" type="idDokument" use="required"/>
  </xs:complexType>


  <xs:complexType name="dokumentDIP" abstract="false">
    <xs:complexContent>
      <xs:extension base="dokument"> </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="inhaltsverzeichnis" abstract="true">
    <xs:sequence/>
  </xs:complexType>

  <xs:complexType name="inhaltsverzeichnisDIP">
    <xs:complexContent>
      <xs:extension base="inhaltsverzeichnis">
        <xs:sequence>
          <xs:element name="ordner" type="ordnerDIP" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element name="datei" type="dateiDIP" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="datei" abstract="true">
    <xs:sequence>
      <xs:element name="name" type="nameDatei"/>
      <xs:element name="originalName" type="originalName" minOccurs="0"/>
      <xs:element name="pruefalgorithmus" type="pruefalgorithmus"/>
      <xs:element name="pruefsumme" type="pruefsumme"/>
      <xs:element name="eigenschaft" type="eigenschaftDatei" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation xml:lang="de">Name und Wert von technischen Eigenschaften der Dateien wie z.B. Felddelemiter.</xs:documentation>
          <xs:documentation xml:lang="en">Name and value of technical properties of the files such as field delimiters.</xs:documentation>
          <xs:documentation xml:lang="fr">Nom et valeur des propriétés techniques des fichiers, p. ex.:séparateur de champs.</xs:documentation>
          <xs:documentation xml:lang="it"/>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="id" type="idDatei" use="required"/>
  </xs:complexType>

  <xs:complexType name="dateiDIP">
    <xs:complexContent>
      <xs:extension base="datei"> </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="ordner" abstract="true">
    <xs:sequence>
      <xs:element name="name" type="nameOrdner"/>
      <xs:element name="originalName" type="originalName" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="id" type="idOrdner" use="required"/>
  </xs:complexType>

  <xs:complexType name="ordnerDIP">
    <xs:complexContent>
      <xs:extension base="ordner">
        <xs:sequence>
          <xs:element name="ordner" type="ordnerDIP" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element name="datei" type="dateiDIP" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="eigenschaftDatei">
    <xs:simpleContent>
      <xs:extension base="eigenschaft">
        <xs:attribute name="name" type="text4" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:simpleType name="umfangDossier">
    <xs:restriction base="text2"/>
  </xs:simpleType>
  <xs:simpleType name="signaturDokument">
    <xs:restriction base="text1"/>
  </xs:simpleType>
  <xs:simpleType name="formatDokument">
    <xs:restriction base="text1"/>
  </xs:simpleType>
  <xs:simpleType name="themaDokument">
    <xs:restriction base="text1"/>
  </xs:simpleType>
  <xs:simpleType name="urheberDokument">
    <xs:restriction base="text1"/>
  </xs:simpleType>
  <xs:simpleType name="verlegerDokument">
    <xs:restriction base="text1"/>
  </xs:simpleType>
  <xs:simpleType name="abdeckungDokument">
    <xs:restriction base="text1"/>
  </xs:simpleType>
</xs:schema>

=== SwissFederalArchives/cmi-viaduc-backend/Test/Manager/Asset.Tests/TestData/IiifSourceData/30653558/header/metadata.xml
<?xml version="1.0" encoding="utf-8"?>
<paket xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:type="paketDIP" schemaVersion="4.1" xsi:schemaLocation="http://bar.admin.ch/gebrauchskopie/v1 gebrauchskopie.xsd" xmlns="http://bar.admin.ch/gebrauchskopie/v1">
  <generierungsdatum>2023-01-27T00:00:00+01:00</generierungsdatum>
  <inhaltsverzeichnis>
    <ordner id="contentRoot638104236070351768">
      <name>content</name>
      <originalName>content</originalName>
      <ordner id="_mUxkNuL5fRXDIoA0ozZqLg_D">
        <name>Fotoalben, II. Kategorie-Presse</name>
        <originalName>Fotoalben, II. Kategorie-Presse</originalName>
        <ordner id="_taVWf1zJIp1FZKolO5Y3wT_D">
          <name>U_m_s_c_h_l_a_g_0000007</name>
          <originalName>U_m_s_c_h_l_a_g_0000007</originalName>
          <datei id="_eBbhmyoh93kqg5Q9mKxvHe">
            <name>00000033.jp2</name>
            <originalName>00000033.jp2</originalName>
            <pruefalgorithmus>MD5</pruefalgorithmus>
            <pruefsumme>08f5941e25fd3e8ffd7c530e8dfbed65</pruefsumme>
          </datei>
          <datei id="_73B7cGbtqziRJC2iwLteKE">
            <name>00000033_PREMIS.xml</name>
            <originalName>00000033_PREMIS.xml</originalName>
            <pruefalgorithmus>MD5</pruefalgorithmus>
            <pruefsumme>df001fe1f0da7cd2f3c9ad05d8bfd969</pruefsumme>
          </datei>
          <datei id="_IycrymMJ1SNt4MkeLC3siH">
            <name>00000034.jp2</name>
            <originalName>00000034.jp2</originalName>
            <pruefalgorithmus>MD5</pruefalgorithmus>
            <pruefsumme>365052f8c83d40d84cab2295b800847e</pruefsumme>
          </datei>
          <datei id="_955fh7hzZRQw6mSgAtRDGN">
            <name>00000034_PREMIS.xml</name>
            <originalName>00000034_PREMIS.xml</originalName>
            <pruefalgorithmus>MD5</pruefalgorithmus>
            <pruefsumme>5c8f780f2c5343f785121f868886fefb</pruefsumme>
          </datei>
        </ordner>
        <ordner id="_zB6EW180t0wV4UUdaTKeD9_D">
          <name>D_o_k_u_m_e_n_t_0000009</name>
          <originalName>D_o_k_u_m_e_n_t_0000009</originalName>
          <datei id="_XWbO7fLO41dM4eLpm3zNU5">
            <name>00000035.jp2</name>
            <originalName>00000035.jp2</originalName>
            <pruefalgorithmus>MD5</pruefalgorithmus>
            <pruefsumme>d5bcbf316ad971cd757eb31369d0c7e9</pruefsumme>
          </datei>
          <datei id="_it74iySrrboN4MxdZvX9ZY">
            <name>00000035_PREMIS.xml</name>
            <originalName>00000035_PREMIS.xml</originalName>
            <pruefalgorithmus>MD5</pruefalgorithmus>
            <pruefsumme>478b5f26ccfa196410598b538ed71a2a</pruefsumme>
          </datei>
          <datei id="_orRFEWHWKLCJgf371va7RS">
            <name>00000036.jp2</name>
            <originalName>00000036.jp2</originalName>
            <pruefalgorithmus>MD5</pruefalgorithmus>
            <pruefsumme>4847c0aa538f2a6410245ebcc4da7419</pruefsumme>
          </datei>
          <datei id="_OZ7pEKhpdz7YsVKYbJORaQ">
            <name>00000036_PREMIS.xml</name>
            <originalName>00000036_PREMIS.xml</originalName>
            <pruefalgorithmus>MD5</pruefalgorithmus>
            <pruefsumme>b5eaf9877fd779589d986fb39f47b898</pruefsumme>
          </datei>
        </ordner>
      </ordner>
      <ordner id="_z5trSXo1v3VvQzSyMF4IXD_D">
        <name>Fotoalben, II. Kategorie-Presse</name>
        <originalName>Fotoalben, II. Kategorie-Presse</originalName>
        <ordner id="_7uWs6hIoIGYeI7gXT4ZegT_D">
          <name>U_m_s_c_h_l_a_g_0000010</name>
          <originalName>U_m_s_c_h_l_a_g_0000010</originalName>
          <datei id="_2ub0CB4GMrTvC2PiyM1PQc">
            <name>00000047.jp2</name>
            <originalName>00000047.jp2</originalName>
            <pruefalgorithmus>MD5</pruefalgorithmus>
            <pruefsumme>a6fa607248d27b0e6606fb51005e0db3</pruefsumme>
          </datei>
          <datei id="_kAnPAEjjzfNCLDaDeB8H3s">
            <name>00000047_PREMIS.xml</name>
            <originalName>00000047_PREMIS.xml</originalName>
            <pruefalgorithmus>MD5</pruefalgorithmus>
            <pruefsumme>ec555abe97fbbbddba214bce8c9c7d25</pruefsumme>
          </datei>
          <datei id="_nHiqdJcMrajZbdcKSCvNLp">
            <name>00000048.jp2</name>
            <originalName>00000048.jp2</originalName>
            <pruefalgorithmus>MD5</pruefalgorithmus>
            <pruefsumme>7274435bb0cb55d3a6cd05e15dcc5c13</pruefsumme>
          </datei>
          <datei id="_4awyYeXZfsKayQE9c8F25K">
            <name>00000048_PREMIS.xml</name>
            <originalName>00000048_PREMIS.xml</originalName>
            <pruefalgorithmus>MD5</pruefalgorithmus>
            <pruefsumme>e9509fdf631a4f496c23b97a744fd419</pruefsumme>
          </datei>
        </ordner>
        <ordner id="_89auFmJd9VvCnrDTtSrc3m_D">
          <name>D_o_k_u_m_e_n_t_0000012</name>
          <originalName>D_o_k_u_m_e_n_t_0000012</originalName>
          <datei id="_Ns6s4zDFoKTzxRlHyTqM6q">
            <name>00000049.jp2</name>
            <originalName>00000049.jp2</originalName>
            <pruefalgorithmus>MD5</pruefalgorithmus>
            <pruefsumme>dc6bbebbc0f252bd8f1d0fbd08e38bd5</pruefsumme>
          </datei>
          <datei id="_bqWtPrRZsxVlEG9nualW1E">
            <name>00000049_PREMIS.xml</name>
            <originalName>00000049_PREMIS.xml</originalName>
            <pruefalgorithmus>MD5</pruefalgorithmus>
            <pruefsumme>54465cdf1d3bff7e739f3892e025d8a0</pruefsumme>
          </datei>
          <datei id="_C1lngApdQCD4JFjnPx8U3c">
            <name>00000050.jp2</name>
            <originalName>00000050.jp2</originalName>
            <pruefalgorithmus>MD5</pruefalgorithmus>
            <pruefsumme>10494d043baca43484e78a498c8e2017</pruefsumme>
          </datei>
          <datei id="_WeqrVI77mUP4XJufk0kQ65">
            <name>00000050_PREMIS.xml</name>
            <originalName>00000050_PREMIS.xml</originalName>
            <pruefalgorithmus>MD5</pruefalgorithmus>
            <pruefsumme>8227f2f19670246d54b3d8eaacb5300d</pruefsumme>
          </datei>
          <datei id="_oXndN5shU4ERB5p5e3Tgzr">
            <name>00000051.jp2</name>
            <originalName>00000051.jp2</originalName>
            <pruefalgorithmus>MD5</pruefalgorithmus>
            <pruefsumme>b4bb9b9b7003d3f95860668faf24d9b6</pruefsumme>
          </datei>
          <datei id="_rEevNJifkC4LgWO9wo9zP4">
            <name>00000051_PREMIS.xml</name>
            <originalName>00000051_PREMIS.xml</originalName>
            <pruefalgorithmus>MD5</pruefalgorithmus>
            <pruefsumme>5b6806d6c66c31b126fc6ee08131c695</pruefsumme>
          </datei>
          <datei id="_B06ineIl2JnjUJuh7B3YOG">
            <name>00000052.jp2</name>
            <originalName>00000052.jp2</originalName>
            <pruefalgorithmus>MD5</pruefalgorithmus>
            <pruefsumme>7cd5c0010cf8be1785f2888638aff287</pruefsumme>
          </datei>
          <datei id="_ngjXVcoGjVwApnNYUPByex">
            <name>00000052_PREMIS.xml</name>
            <originalName>00000052_PREMIS.xml</originalName>
            <pruefalgorithmus>MD5</pruefalgorithmus>
            <pruefsumme>f96e965295696b9f5ca4435270f2feff</pruefsumme>
          </datei>
        </ordner>
      </ordner>
      <ordner id="_U1Q2qc6tW19iBdaWmtNImT_D">
        <name>Fotoalben, II. Kategorie-Presse</name>
        <originalName>Fotoalben, II. Kategorie-Presse</originalName>
        <ordner id="_T09Zd4fr3gkhz6kxCfCXz3_D">
          <name>U_m_s_c_h_l_a_g_0000002</name>
          <originalName>U_m_s_c_h_l_a_g_0000002</originalName>
          <datei id="_s0TXeLQ9pOWH22DXzh19f5">
            <name>00000009.jp2</name>
            <originalName>00000009.jp2</originalName>
            <pruefalgorithmus>MD5</pruefalgorithmus>
            <pruefsumme>1f5c7a293849609ad9a6e9209c2c886a</pruefsumme>
          </datei>
          <datei id="_dY3ODuf7ASaTCwfkqswGGD">
            <name>00000009_PREMIS.xml</name>
            <originalName>00000009_PREMIS.xml</originalName>
            <pruefalgorithmus>MD5</pruefalgorithmus>
            <pruefsumme>37c056288a7cd17cb954c88f9954f94c</pruefsumme>
          </datei>
          <datei id="_mk18IdtqC5mYHVTtArBeF5">
            <name>00000010.jp2</name>
            <originalName>00000010.jp2</originalName>
            <pruefalgorithmus>MD5</pruefalgorithmus>
            <pruefsumme>5f2bd14b4d7a85c455e6501111c1ce5f</pruefsumme>
          </datei>
          <datei id="_QRHP049r2Fq7DlYrz5Run0">
            <name>00000010_PREMIS.xml</name>
            <originalName>00000010_PREMIS.xml</originalName>
            <pruefalgorithmus>MD5</pruefalgorithmus>
            <pruefsumme>1379cdeee00258465aef908ce83186bf</pruefsumme>
          </datei>
        </ordner>
        <ordner id="_Tt845F3AcnO16RfzBSfbAB_D">
          <name>Brückensprengung</name>
          <originalName>Brückensprengung</originalName>
          <datei id="_4VAgaWp3aW2mpEgMyw4r5h">
            <name>00000011.jp2</name>
            <originalName>00000011.jp2</originalName>
            <pruefalgorithmus>MD5</pruefalgorithmus>
            <pruefsumme>223fb91b6fbfe1a6e07a41fcd891d9ea</pruefsumme>
          </datei>
          <datei id="_88owJkfwAGPXYHRHOtQi6x">
            <name>00000011_PREMIS.xml</name>
            <originalName>00000011_PREMIS.xml</originalName>
            <pruefalgorithmus>MD5</pruefalgorithmus>
            <pruefsumme>fc453d6a7e5168e4d014d63ac4837e6d</pruefsumme>
          </datei>
          <datei id="_rtEguCWcbzqtfNhC5qjgvY">
            <name>00000012.jp2</name>
            <originalName>00000012.jp2</originalName>
            <pruefalgorithmus>MD5</pruefalgorithmus>
            <pruefsumme>2941716b4b179581c603233f11cf6d66</pruefsumme>
          </datei>
          <datei id="_Lvq93TPGHUv8WZ5V9BqDpN">
            <name>00000012_PREMIS.xml</name>
            <originalName>00000012_PREMIS.xml</originalName>
